name = "wolfstar-rocks"
compatibility_date = "2025-09-20"
compatibility_flags = [ "nodejs_compat" ]
main = "./dist/server/index.mjs"

[route]
pattern = "wolfstar.rocks"
custom_domain = true

[observability.logs]
enabled = true

[version_metadata]
binding = "CF_VERSION_METADATA"

[assets]
directory = "./dist/public/"
binding = "ASSETS"

[env.beta]
name = "wolfstar-rocks-beta"

[env.beta.assets]
directory = "./dist/public/"
binding = "ASSETS"

[env.staging]
name = "wolfstar-rocks-staging"

[env.staging.assets]
directory = "./dist/public/"
binding = "ASSETS"
