name = "wolfstar-rocks"
compatibility_date = "2025-09-20"
compatibility_flags = [
  "nodejs_als",
  "nodejs_compat"
]
main = "./dist/server/index.mjs"

[route]
pattern = "wolfstar.rocks"
custom_domain = true

[observability.logs]
enabled = true

[version_metadata]
binding = "CF_VERSION_METADATA"

[assets]
directory = "./dist/public/"
binding = "ASSETS"

[[kv_namespaces]]
binding = "OG_IMAGE_CACHE"
id = "594b9f219bc94c14b55a0fd7d90dc691"

[env.staging.route]
pattern = "staging.wolfstar.rocks"
custom_domain = true

[env.beta.route]
pattern = "beta.wolfstar.rocks"
custom_domain = true
